### ISSUE TITLE
code

### ISSUE THREAD

**Issue by fsh2017** [Tsunehiko/lol-v2t#1]
Hi Tsunehiko, I have read your paper and it impresses me, but I can't find the code of your masking model. I am wondering whether you could kindly offer me the source program?

**Comment by tsunehiko** [comment]
I'm sorry for the late reply.
I publish the masking code in https://github.com/Tsunehiko/create-lol-v2t, but I didn't prepare the readme (I'll do my best to write it soon).
I think that you can easily implement the masking process using python replace method. For doing, you have to prepare the dictionary for the replacement (I created it manually: https://github.com/Tsunehiko/create-lol-v2t/blob/master/dataset/dictionary.json )
If you are referring to a different part of the code, please contact me again.
